routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('home');
});

Auth::routes([
    'regiter' => false
]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'startPage'])->name('home');
Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'index'])->name('dashboard');

Route::middleware('auth')->group(function(){
    // resource routes
    Route::resource('users', \App\Http\Controllers\UserController::class);
    Route::resource('sales', \App\Http\Controllers\SaleController::class);
    Route::resource('products', \App\Http\Controllers\ProductController::class);
    Route::resource('payments', \App\Http\Controllers\PaymentController::class);
    Route::resource('purchases', \App\Http\Controllers\PurchaseController::class);
    Route::resource('suppliers', \App\Http\Controllers\SupplierController::class);
    Route::resource('categories', \App\Http\Controllers\CategoryController::class);
    Route::resource('warehouses', \App\Http\Controllers\WarehouseController::class);
    Route::resource('roles-permissions', \App\Http\Controllers\RolePermissionController::class);

    // datatable routes
    Route::get('datatable/users', [\App\Http\Controllers\DataTablesController::class, 'getUsers']);
    Route::get('datatable/sales', [\App\Http\Controllers\DataTablesController::class, 'getSales']);
    Route::get('datatable/payments', [\App\Http\Controllers\DataTablesController::class, 'getPayments']);
    Route::get('datatable/products', [\App\Http\Controllers\DataTablesController::class, 'getProducts']);
    Route::get('datatable/suppliers', [\App\Http\Controllers\DataTablesController::class, 'getSuppliers']);
    Route::get('datatable/purchases', [\App\Http\Controllers\DataTablesController::class, 'getPurchases']);
    Route::get('datatable/activities', [\App\Http\Controllers\DataTablesController::class, 'getActivities']);
    Route::get('datatable/categories', [\App\Http\Controllers\DataTablesController::class, 'getCategories']);
    Route::get('datatable/warehouses', [\App\Http\Controllers\DataTablesController::class, 'getWarehouses']);
    Route::get('datatable/roles-permissions', [\App\Http\Controllers\DataTablesController::class, 'getRoles']);

    // additional routes
    Route::get('getproducts', [\App\Http\Controllers\SaleController::class, 'getProducts']);
    Route::get('get/sale/{id}', [\App\Http\Controllers\SaleController::class, 'getSale']);
    Route::get('get/purchase/{id}', [\App\Http\Controllers\PurchaseController::class, 'getPurchase']);
    Route::put('password/reset/manual', [\App\Http\Controllers\UserController::class, 'resetPassword']);
    Route::get('activities', [\App\Http\Controllers\ActivityController::class, 'index'])->name('activities.index');
    Route::get('get/permission/{id}', [\App\Http\Controllers\RolePermissionController::class, 'getPermission']);
    Route::get('get/user/{id}', [\App\Http\Controllers\RolePermissionController::class, 'getUserRole']);
    Route::post('roles-permissions/setup-permissions/{id}', [\App\Http\Controllers\RolePermissionController::class, 'updatePermission']);
    Route::post('roles-permissions/assign-role', [\App\Http\Controllers\RolePermissionController::class, 'asignRoleUser']);

    // report route
    Route::get('report/sales', [\App\Http\Controllers\ReportController::class, 'salesReport'])->name('reports.sales.index');
    Route::get('get/report/all', [\App\Http\Controllers\ReportController::class, 'getSalesAll']);
    Route::get('get/report/product', [\App\Http\Controllers\ReportController::class, 'getSalesProduct']);
    Route::get('report/purchases', [\App\Http\Controllers\ReportController::class, 'reportPurchasePage']);
    Route::get('report/purchases/filter', [\App\Http\Controllers\ReportController::class, 'getReportPurchases']);

});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, SoftDeletes, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'phone',
        'address',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function transactions()
    {
        return $this->hasMany(Transaction::class);
    }

    public function activities() {
        return $this->hasMany(Activity::class);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\Activity;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('users.users');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'phone' => ['required', 'unique:users'],
            'address' => ['required'],
            'password' => ['required', 'string', 'min:6', 'confirmed'],
        ]);

        $user = User::create([
            'name' => $request->name,
            'email' => $request->email,
            'phone' => $request->phone,
            'address' => $request->address,
            'password' => Hash::make($request->password),
        ]);

        Activity::create([
            'user_id' =>  Auth::id(),
            'activity' => "Menambahkan User Baru (" . $user->name. ")",
        ]);

        return $user;
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('users.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255'],
            'phone' => ['required',],
            'address' => ['required'],
        ]);

        $user->update([
            'name' => $request->name,
            'email' => $request->email,
            'phone' => $request->phone,
            'address' => $request->address,
        ]);

        Activity::create([
            'user_id' =>  Auth::id(),
            'activity' => "Mengubah User (" . $user->name. ")",
        ]);

        return redirect()->back()->with('success', 'Profil Anda Berhasil Diperbarui!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        Activity::create([
            'user_id' =>  Auth::id(),
            'activity' => "Menghapus User (" . $user->name. ")",
        ]);

        $user->delete();

        return response()->json($user);
    }

    public function resetPassword(Request $request)
    {
        $request->validate([
            'password' => ['required', 'string', 'min:6', 'confirmed'],
        ]);

        $user = $request->user();

        $user->update([
            'password' => $request->password,
        ]);

        return redirect()->back()->with('success', 'Password Anda Berhasil Diperbaharui');
    }
}

resources/views/users/activities.blade.php
@extends('layouts.app')
@section('title', 'Aktifitas')
@section('content-title', 'Aktifitas')
@section('card-header', 'Log Aktifitas User')
@section('breadcrumb', 'Aktifitas')
@section('sub-breadcrumb', 'Log Aktifitas User')

@section('content')
    <div class="row">
        <div class="col">
            <table class="table table-bordered text-dark text-center table-sm table-striped" id="table">
                <thead class="bg-dark">
                    <tr>
                        <th>No</th>
                        <th>Tanggal</th>
                        <th>User</th>
                        <th>Aktifitas</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>

@endsection

@section('css')
    <link rel="stylesheet" href="{{asset('adminLTE/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css')}}">
    <link rel="stylesheet" href="{{asset('adminLTE/plugins/datatables-responsive/css/responsive.bootstrap4.min.css')}}">
    <link rel="stylesheet" href="{{asset('adminLTE/plugins/datatables-buttons/css/buttons.bootstrap4.min.css')}}">
@endsection

@push('script')
    {{-- datatables script --}}
    <script src="{{asset('adminLTE/plugins/datatables/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('adminLTE/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
    <script src="{{asset('adminLTE/plugins/datatables-responsive/js/dataTables.responsive.min.js')}}"></script>
    <script src="{{asset('adminLTE/plugins/datatables-responsive/js/responsive.bootstrap4.min.js')}}"></script>

    <script>
        var api = '{{ url('datatable/activities') }}';
        $(function () {
            $('#table').DataTable({
                processing: true,
                responsive: true,
                serverSide: true,
                ajax: api,
                columns: [
                    { data: 'DT_RowIndex', name: 'DT_RowIndex' },
                    { data: 'created_at', name: 'created_at' },
                    { data: 'user', name: 'user' },
                    { data: 'activity', name: 'activity' },
                ]
            })
        });
     </script>
@endpush

resources/views/users/edit.blade.php
@extends('layouts.app')
@section('title', 'Profil')
@section('content-title', 'Profil')
@section('card-header', 'Profil')
@section('breadcrumb', 'Profil')
@section('sub-breadcrumb', 'Profil')

@section('content')
<div class="row">
    <div class="col-5">
        <form action="{{ route( 'users.update', ['user' => $user->id ] ) }}" method="POST">
            @csrf
            @method('PUT')
            <div class="card">
                <div class="card-header bg-secondary">
                    <h4 class="card-title">Biodata</h4>
                </div>
                <div class="card-body">
                    <div class="mb-3">
                        <label for="name" class="form-label">Nama Lengkap</label>
                        <input type="text" name="name" id="name" class="form-control" placeholder="Isi nama lengkap" aria-describedby="user_name" value="{{ old('name', $user->name) }}">
                        @error('name')
                        <small class="text-danger">{{$message}}</small>
                        @enderror
                    </div>
                    <div class="mb-3">
                        <label for="email" class="form-label">Email</label>
                        <input type="email" class="form-control" name="email" id="email" aria-describedby="emailHelpId" placeholder="Isi email valid" value="{{ old('email', $user->email) }}">
                        @error('email')
                        <small class="text-danger">{{$message}}</small>
                        @enderror
                    </div>
                    <div class="mb-3">
                        <label for="phone" class="form-label">Telepon</label>
                        <input type="text" name="phone" id="phone" class="form-control" placeholder="Isi nomor telepon" aria-describedby="phonehelpId" value="{{ old('phone', $user->phone) }}">
                        @error('phone')
                            <small class="text-danger">{{$message}}</small>
                        @enderror
                    </div>
                    <div class="mb-3">
                        <label for="address" class="form-label">Alamat</label>
                        <textarea class="form-control" name="address" id="address" rows="2">{{ old('address', $user->address) }}</textarea>
                        @error('address')
                            <small class="text-danger">{{$message}}</small>
                        @enderror
                    </div>
                </div>
                <div class="card-footer text-center">
                    <button class="btn btn-primary" type="submit">Update</button>
                </div>
            </div>
        </form>
        <form action="{{ url('password/reset/manual') }}" method="POST">
            @csrf
            @method('PUT')
            <div class="card">
                <div class="card-header bg-secondary">
                    <h4 class="card-title">Keamanan</h4>
                </div>
                <div class="card-body row">
                    <div class="col-6">
                        <label for="password" class="form-label">Password</label>
                        <input type="password" name="password" id="password" class="form-control" autocomplete="new-password">
                        <small id="helpId" class="text-muted">Masukan password minimal 6 digit</small>
                    </div>
                    <div class="col-6">
                        <label for="password_confirmation" class="form-label">Konfirmasi Password</label>
                        <input type="password" name="password_confirmation" id="password_confirmation" class="form-control" autocomplete="new-password">
                    </div>
                </div>
                <div class="card-footer text-center">
                    <button class="btn btn-danger">Reset</button>
                </div>
            </div>
        </form>
    </div> <!-- col-5 end -->
</div>
@endsection

@push('script')
    {{-- sweetalert CDN --}}
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    @if (Session::get('success'))
        <script>
            Swal.fire({
                title: 'Mantap',
                icon: 'success',
                text: '{!! Session::get('success') !!}',
            });
        </script>
    @endif

    @error('password')
    <script>
        Swal.fire({
            title: 'Ooops',
            icon: 'error',
            text: '{!! $message !!}',
        });
    </script>
    @enderror

@endpush

resources/views/users/show.blade.php
{{-- modal box --}}
<div class="modal fade" id="showModal" tabindex="-1" aria-labelledby="showModalLabel" aria-hidden="true">
    <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header bg-primary">
                    <h5 class="modal-title text-center" id="exampleModalLabel">Curriculum Vitae</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="card">
                        <div class="card-header bg-secondary">
                            <h5 class="card-title">Biodata</h5>
                        </div>
                        <div class="card-body">
                            <table class="table">
                                <tr>
                                    <th>Nama Lengkap</th>
                                    <td>: @{{data.name}}</td>
                                </tr>
                                <tr>
                                    <th>Email</th>
                                    <td>: @{{data.email}}</td>
                                </tr>
                                <tr>
                                    <th>Telepon</th>
                                    <td>: @{{data.phone}}</td>
                                </tr>
                                <tr>
                                    <th>Alamat</th>
                                    <td>: @{{data.address}}</td>
                                </tr>
                            </table>
                        </div>
                    </div>

                </div>
            </div>
    </div>
</div>
{{-- modal box end --}}

resources/views/users/users.blade.php
@extends('layouts.app')
@section('title', 'User')
@section('content-title', 'User')
@section('card-header', 'Daftar User')
@section('breadcrumb', 'User')
@section('sub-breadcrumb', 'Daftar User')
@section('content')
    <div class="row mb-2">
        <div class="col-sm-2">
            <a href="#" @click="create()" class="btn btn-primary">Tambah User</a>
        </div>
    </div>
    <hr>
    {{-- data content --}}
    <table class="table table-bordered table-sm text-center w-100" id="table">
        <thead class="bg-dark">
            <th>No</th>
            <th>Registrasi</th>
            <th>Nama</th>
            <th>Email</th>
            <th>Telepon</th>
            <th>Role</th>
            <th>Opsi</th>
        </thead>
    </table>
    {{-- data content end --}}

    {{-- modal box --}}
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <form :action="action" method="POST" @submit.prevent="store($event)">
                @csrf
                <div class="modal-content">
                    <div class="modal-header bg-primary">
                        <h5 class="modal-title text-center" id="exampleModalLabel"></h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="card">
                            <div class="card-header bg-secondary">
                                <h5 class="card-title">Biodata</h5>
                            </div>
                            <div class="card-body row">
                                <div class="col-4">
                                    <label for="name" class="form-label">Nama</label>
                                    <input type="text" name="name" id="name" class="form-control">
                                </div>
                                <div class="col-4">
                                    <label for="email" class="form-label">Email</label>
                                    <input type="email" class="form-control" name="email" id="email">
                                </div>
                                <div class="col-4">
                                    <label for="phone" class="form-label">Telepon</label>
                                    <input type="text" name="phone" id="phone" class="form-control">
                                </div>
                                <div class="col-12">
                                    <label for="address" class="form-label">Alamat</label>
                                    <textarea class="form-control" name="address" id="address" rows="3"></textarea>
                                </div>
                            </div>
                        </div>
                        <div class="card">
                            <div class="card-header bg-secondary">
                                <h5 class="card-title">Keamanan</h5>
                            </div>
                            <div class="card-body row">
                                <div class="col-6">
                                    <label for="password" class="form-label">Password</label>
                                    <input type="password" name="password" id="password" class="form-control" autocomplete="new-password">
                                    <small id="helpId" class="text-muted">Masukan password minimal 6 digit</small>
                                </div>
                                <div class="col-6">
                                    <label for="password_confirmation" class="form-label">Konfirmasi Password</label>
                                    <input type="password" name="password_confirmation" id="password_confirmation" class="form-control" autocomplete="new-password">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer text-center">
                        <button type="submit" class="btn btn-primary">Simpan</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    {{-- modal box end --}}

    {{-- modal box show --}}
    @include('users.show')
    {{-- modal box show end --}}
@endsection

@section('css')
    <link rel="stylesheet" href="{{asset('adminLTE/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css')}}">
    <link rel="stylesheet" href="{{asset('adminLTE/plugins/datatables-responsive/css/responsive.bootstrap4.min.css')}}">
    <link rel="stylesheet" href="{{asset('adminLTE/plugins/datatables-buttons/css/buttons.bootstrap4.min.css')}}">
@endsection

@push('script')
    {{-- datatables script --}}
    <script src="{{asset('adminLTE/plugins/datatables/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('adminLTE/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
    <script src="{{asset('adminLTE/plugins/datatables-responsive/js/dataTables.responsive.min.js')}}"></script>
    <script src="{{asset('adminLTE/plugins/datatables-responsive/js/responsive.bootstrap4.min.js')}}"></script>

    {{-- sweetalert CDN --}}
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script>
        var action = '{{url('users')}}';
        var api = '{{url('datatable/users')}}';
        var columns = [
            { data: "DT_RowIndex", name: "DT_RowIndex" },
            { data: "created_at", name: "created_at"},
            { data: "name", name: "name" },
            { data: "email", name: "email" },
            { data: "phone", name: "phone" },
            { data: "roles", name: "roles" },
            { data: "action", name: "action", orderable:false, searchable: false }
        ];

        // vue js instance
        var app = new Vue({
            el: '#app',
            data: {
                datas: [],
                data: {},
                action: action,
                api: api,
            },
            mounted: function () {
                this.datatable();
            },
            methods: {
                datatable() {
                    const _this = this;
                    _this.table = $("#table")
                        .DataTable({
                            ajax: {
                                url: _this.api,
                                type: "GET",
                            },
                            columns,
                        })
                        .on("xhr", function () {
                            _this.datas = _this.table.ajax.json().data;
                        });
                },
                create() {
                    this.data = {};
                    this.method = false;
                    this.formPassword = true;
                    $("#exampleModal").modal();
                    $(".modal-title").text("Tambah Karyawan");
                },
                store(event) {
                    axios
                        .post(action, new FormData($(event.target)[0]))
                        .then((response) => {
                            $("#exampleModal").modal("hide");
                            Swal.fire({
                                title: 'Mantap',
                                icon: 'success',
                                text: 'Pengguna Baru Berhasil Ditambahkan!'
                            });
                            this.table.ajax.reload();
                        })
                        .catch(function (error) {
                            console.log(error)
                            if (error.response) {
                                var message_error = error.response.data.errors;
                                var error_element = "";
                                $.each(
                                    message_error,
                                    function (indexInArray, valueOfElement) {
                                        error_element += `<div clas='text-danger'> ${valueOfElement}</div> <br>`;
                                    }
                                );

                                Swal.fire({
                                    title: "Gagal!",
                                    icon: "error",
                                    html: error_element,
                                    confirmButtonText: "Ulangi",
                                });
                            }
                        });
                },
                show(e, id) {
                    const _this = this;
                    $("#showModal").modal();
                    _this.data = _this.datas[id];
                    console.log(_this.data)
                },
                destroy(event, id) {
                    Swal.fire({
                        title: 'Are you sure?',
                        text: "You won't be able to revert this!",
                        icon: 'warning',
                        showCancelButton: true,
                        confirmButtonColor: '#3085d6',
                        cancelButtonColor: '#d33',
                        confirmButtonText: 'Yes, delete it!'
                    }).then((result) => {
                        if (result.isConfirmed) {
                            id - 1;
                            axios.delete(action + '/' + id);
                            Swal.fire(
                                'Deleted!',
                                'Your data has been deleted.',
                                'success'
                            )
                            this.table.ajax.reload();
                        }
                    });
                },

            },
        })
    </script>
@endpush