routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('home');
});

Auth::routes([
    'regiter' => false
]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'startPage'])->name('home');
Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'index'])->name('dashboard');

Route::middleware('auth')->group(function(){
    // resource routes
    Route::resource('users', \App\Http\Controllers\UserController::class);
    Route::resource('sales', \App\Http\Controllers\SaleController::class);
    Route::resource('products', \App\Http\Controllers\ProductController::class);
    Route::resource('payments', \App\Http\Controllers\PaymentController::class);
    Route::resource('purchases', \App\Http\Controllers\PurchaseController::class);
    Route::resource('suppliers', \App\Http\Controllers\SupplierController::class);
    Route::resource('categories', \App\Http\Controllers\CategoryController::class);
    Route::resource('warehouses', \App\Http\Controllers\WarehouseController::class);
    Route::resource('roles-permissions', \App\Http\Controllers\RolePermissionController::class);

    // datatable routes
    Route::get('datatable/users', [\App\Http\Controllers\DataTablesController::class, 'getUsers']);
    Route::get('datatable/sales', [\App\Http\Controllers\DataTablesController::class, 'getSales']);
    Route::get('datatable/payments', [\App\Http\Controllers\DataTablesController::class, 'getPayments']);
    Route::get('datatable/products', [\App\Http\Controllers\DataTablesController::class, 'getProducts']);
    Route::get('datatable/suppliers', [\App\Http\Controllers\DataTablesController::class, 'getSuppliers']);
    Route::get('datatable/purchases', [\App\Http\Controllers\DataTablesController::class, 'getPurchases']);
    Route::get('datatable/activities', [\App\Http\Controllers\DataTablesController::class, 'getActivities']);
    Route::get('datatable/categories', [\App\Http\Controllers\DataTablesController::class, 'getCategories']);
    Route::get('datatable/warehouses', [\App\Http\Controllers\DataTablesController::class, 'getWarehouses']);
    Route::get('datatable/roles-permissions', [\App\Http\Controllers\DataTablesController::class, 'getRoles']);

    // additional routes
    Route::get('getproducts', [\App\Http\Controllers\SaleController::class, 'getProducts']);
    Route::get('get/sale/{id}', [\App\Http\Controllers\SaleController::class, 'getSale']);
    Route::get('get/purchase/{id}', [\App\Http\Controllers\PurchaseController::class, 'getPurchase']);
    Route::put('password/reset/manual', [\App\Http\Controllers\UserController::class, 'resetPassword']);
    Route::get('activities', [\App\Http\Controllers\ActivityController::class, 'index'])->name('activities.index');
    Route::get('get/permission/{id}', [\App\Http\Controllers\RolePermissionController::class, 'getPermission']);
    Route::get('get/user/{id}', [\App\Http\Controllers\RolePermissionController::class, 'getUserRole']);
    Route::post('roles-permissions/setup-permissions/{id}', [\App\Http\Controllers\RolePermissionController::class, 'updatePermission']);
    Route::post('roles-permissions/assign-role', [\App\Http\Controllers\RolePermissionController::class, 'asignRoleUser']);

    // report route
    Route::get('report/sales', [\App\Http\Controllers\ReportController::class, 'salesReport'])->name('reports.sales.index');
    Route::get('get/report/all', [\App\Http\Controllers\ReportController::class, 'getSalesAll']);
    Route::get('get/report/product', [\App\Http\Controllers\ReportController::class, 'getSalesProduct']);
    Route::get('report/purchases', [\App\Http\Controllers\ReportController::class, 'reportPurchasePage']);
    Route::get('report/purchases/filter', [\App\Http\Controllers\ReportController::class, 'getReportPurchases']);

});

app/Models/Sale.php
<?php

namespace App\Models;

use DateTimeInterface;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Sale extends Model
{
    use HasFactory, SoftDeletes;
    protected $guarded = [];

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('d-m-Y');
    }

    public function products()
    {
        return $this->belongsToMany(Product::class)->withPivot('quantity')->withTrashed();
    }
}

app/Http/Controllers/SaleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Sale;
use App\Models\Product;
use Illuminate\Http\Request;

class SaleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->authorize('lihat penjualan');

        $products = Product::where('stock', '>', 0)->get();

        // testing mode
        return view('transactions.sales.sales-test', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('tambah penjualan');

        $products = Product::where('stock', '!=', 0)->get();

        return view('transactions.sales.create', compact('products'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreSaleRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->authorize('tambah penjualan');

        $request->validate([
            'total' => ['required'],
            'pembayaran' => ['required'],
            'produk' => ['required'],
            'quantity' => ['required']
        ]);

        $products = [];
        foreach ($request->produk as $key => $value) {
            $products[$value] = ["quantity" => $request->quantity[$key] ];
        }

        $sale = new Sale();
        $sale->total_price = $this->unFormatCurrency($request->total);
        $sale->payment = $request->pembayaran;
        $sale->code = "SO" . date('ymdhis');
        $sale->save();

        $sale->products()->sync($products);

        // kurangi stok sesuai quantity dari sale yang beru saya disimpan
        foreach ($sale->products as $p) {
            $product = Product::find($p->id);
            $product->stock -= $p->pivot->quantity;
            $product->save();
        }

        return response()->json( $sale->load('products') );
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Sale  $sale
     * @return \Illuminate\Http\Response
     */
    public function show(Sale $sale)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Sale  $sale
     * @return \Illuminate\Http\Response
     */
    public function edit(Sale $sale)
    {
        // handle ajax untuk mengambil satu data penjualan untuk edit
        return response()->json( $sale->load('products') );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdateSaleRequest  $request
     * @param  \App\Models\Sale  $sale
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Sale $sale)
    {
        $this->authorize('edit penjualan');

        $request->validate([
            'total' => ['required'],
            'pembayaran' => ['required'],
            'produk' => ['required'],
            'quantity' => ['required']
        ]);

        // return $sale->load('products');

        // kembalikan stok produk ke semula
        foreach ($sale->products as $p) {
                $product = Product::find($p->id);
                $product->stock += $p->pivot->quantity;
                $product->save();
        }

        // isi tabel sales
        $sale->total_price = $this->unFormatCurrency($request->total);
        $sale->payment = $request->pembayaran;
        $sale->save();

        // maping request produk sesuai dengan tempate method sync cth: $user->roles()->sync([1 => ['expires' => true], 2, 3]);
        $products = [];
        foreach ($request->produk as $key => $value) {
            $products[$value] = ["quantity" => $request->quantity[$key] ];
        }

        //  isi tabel pivot dengan method sync
        $sale->products()->sync($products);

        // kurangi stok sesuai quantity dari sale yang beru saya disimpan
        foreach ($request->produk as $key => $value) {
            $product = Product::find($value);
            $product->stock -= $request->quantity[$key];
            $product->save();
        }

        return response()->json( $sale->load('products') );
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Sale  $sale
     * @return \Illuminate\Http\Response
     */
    public function destroy(Sale $sale)
    {
        $this->authorize('hapus penjualan');

        $sale->products()->detach();

        $sale->delete();

        return response("Penjualan berhasil dihapus");
    }

    public function getSale($id)
    {
        $this->authorize('lihat penjualan');

        $sale = Sale::where('id', $id)->with('products')->first();

        return response()->json($sale);
    }

    public function getProducts()
    {
        $products = Product::where('stock', '>', 0)->get();
        return $products;
    }

    public function unFormatCurrency($num)
    {
        return intval(preg_replace('/[^\d\.]/', '', $num));
    }

}

resources/views/transactions/sales/create.blade.php
@extends('layouts.app')
@section('title', 'Penjualan')
@section('content-title', 'Penjualan')
@section('card-header', 'Kasir')
@section('breadcrumb', 'Penjualan')
@section('sub-breadcrumb', 'Kasir')

@section('content')
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
<div class="card">
    <div class="card-header">
        <h4 class="card-title">Penjualan Baru</h4>
    </div>
    <div class="card-body">
        <form action="{{ route('sales.store') }}" method="POST">
            @csrf
            <div class="row">
                <div class="col-7 card">
                    <div class="card-header">
                        <div class="mb-3">
                          <label for="" class="form-label">Pilih Produk</label>
                          <select class="form-control select2" onchange="app.tambahOrder(event)">
                            <option value="">Pilih Produk</option>
                            @foreach ($products as $p)
                            <option value="{{$p->id}}">{{ $p->code }} - {{ $p->name }}</option>
                            @endforeach
                          </select>
                        </div>
                    </div>
                    <div class="card-body">
                       <table class="table table-sm">
                           <thead class="text-center">
                               <th>Kode</th>
                               <th>Nama</th>
                               <th>Harga</th>
                               <th>Stok</th>
                               <th>Jumlah</th>
                               <th>Total</th>
                               <th>Aksi</th>
                           </thead>
                           <tbody class="text-center">
                               <tr v-for="(order, index) in orders">
                                   <input type="hidden" name="produk[]" value="1">
                                    <td>
                                        <input type="text" class="form-control form-control-sm" id="kode" :value="order.code" readonly>
                                    </td>
                                    <td>
                                        <input type="text" class="form-control form-control-sm" id="name" :value="order.name" readonly>
                                    </td>
                                    <td>
                                        <input type="text" class="form-control form-control-sm" id="harga" :value="order.price" readonly>
                                    </td>
                                    <td>
                                        <input type="text" class="form-control form-control-sm" id="stock" :value="order.stock" readonly>
                                    </td>
                                    <td>
                                        <input type="number" name="quantity[]" v-model="order.quantity" class="form-control form-control-sm" id="quantity" @keyup="hitungTotal($event, index)">
                                    </td>
                                    <td>
                                        <input type="text" class="form-control form-control-sm" :value="order.total" id="subtotal" readonly>
                                    </td>
                                    <td>
                                        <button type="button" class="btn btn-sm btn-danger" @click="hapusOrder(index, order)"><i class="fas fa-trash"></i></button>
                                    </td>
                               </tr>
                           </tbody>
                           <tfoot>
                               <tr>
                                   <th colspan="4" class="text-right">Subtotal</th>
                                   <td colspan="2">
                                       <input type="number" class="form-control form-control-sm" name="total" :value="grandTotal" readonly>
                                   </td>
                               </tr>
                           </tfoot>
                       </table>
                    </div>
                </div>
                <div class="col-5 card">
                    <div class="card-header">
                        <p class="card-title">Detil Transaksi</p>
                    </div>
                    <div class="card-body">
                       <div class="row">
                           <div class="col-6 mb-2">
                                <label for="grandtotal">Grand Total</label>
                           </div>
                           <div class="col-6 mb-2">
                                <input type="number" class="form-control form-control-sm" name="grandtotal" :value="grandTotal" readonly>
                           </div>
                           <div class="col-6 mb-2">
                                <label for="pembayaran">Pembayaran</label>
                           </div>
                           <div class="col-6 mb-2">
                                <input type="number" class="form-control form-control-sm" name="pembayaran" v-model="pembayaran" id="pembayaran">
                           </div>
                           <div class="col-6 mb-2">
                                <label for="kembalian">Kembalian</label>
                           </div>
                           <div class="col-6 mb-2">
                                <input type="number" class="form-control form-control-sm" name="kembalian" :value="(pembayaran-grandTotal)" readonly>
                           </div>
                       </div>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Bayar</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

@section('css')
    <!-- Select2 -->
    <link rel="stylesheet" href="{{asset('adminLTE/plugins/select2/css/select2.min.css')}}">
    <link rel="stylesheet" href="{{asset('adminLTE/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css')}}">
@endsection

@push('script')
     <!-- Select2 -->
     <script src="{{asset('adminLTe/plugins/select2/js/select2.full.min.js')}}"></script>
     <!-- Manual Script -->
     <script>
        var daftarProduk = JSON.parse('{!! $products !!}')
        var app = new Vue({
            el: '#app',
            data: {
                datas: [], // variable untuk menyimpan seluruh data produk
                data: {},
                orders: [], // variable untuk menyimpan satu produk untuk crud
                grandTotal: 0,
                pembayaran: 0,
            },
            mounted: function () {
                // select2
                $('.select2').select2({ theme: 'bootstrap4'})
            },
            methods: {
                tambahOrder(e) {
                    const id = e.target.value -1;
                    const produk = daftarProduk[id]
                    this.orders.push({
                        product_id : produk.id,
                        code: produk.code,
                        name: produk.name,
                        price: produk.price,
                        stock: produk.stock,
                        quantity: 1,
                        total: produk.price * 1
                    });
                    this.hitungGrandTotal();
                },
                hapusOrder(index, order) {
                    var idx = this.orders.indexOf(order);
                    console.log(idx, index);
                    if (idx > -1) {
                        this.orders.splice(idx, 1);
                    }
                    this.hitungGrandTotal();
                },
                hitungGrandTotal() {
                    var subtotal, total;
                    subtotal = this.orders.reduce(function (sum, order) {
                        var lineTotal = parseFloat(order.total);
                        if (!isNaN(lineTotal)) {
                            return sum + lineTotal;
                        }
                    }, 0);
                    this.grandTotal = subtotal;
                },
                hitungTotal(e, index) {
                    // dapatkan value
                    var value = e.target.value;
                    // ambil harga orders sesuai index
                    var price = this.orders[index].price;
                    // hitung ulang total orders
                    var result = parseInt(price) * parseInt(value);
                    // ubah isi total pada orders
                    this.orders[index].total = result;
                    this.hitungGrandTotal();
                },

            },
        })
    </script>
@endpush

resources/views/transactions/sales/edit.blade.php
<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editModalLabel">Edit Penjualan</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form :action="action" method="POST" @submit.prevent="update(data.id)">
                @csrf
                <div class="row">
                    <div class="col-7 card">
                        <div class="card-header">
                            <div class="mb-3">
                              <label for="" class="form-label">Pilih Produk</label>
                              <select class="form-control select3" onchange="app.tambahOrder(event)" disabled>
                                <option value="">Pilih Produk</option>
                                @foreach ($products as $p)
                                <option value="{{$p->id}}">{{ $p->code }} - {{ $p->name }}</option>
                                @endforeach
                              </select>
                            </div>
                        </div>
                        <div class="card-body">
                           <table class="table table-sm">
                               <thead class="text-center">
                                   <th>Kode</th>
                                   <th>Nama</th>
                                   <th>Harga</th>
                                   <th>Stok</th>
                                   <th>Jumlah</th>
                                   <th>Total</th>
                                   <th>Aksi</th>
                               </thead>
                               <tbody class="text-center">
                                   <tr v-for="(order, index) in orders">
                                       <input type="hidden" name="produk[]" value="1">
                                        <td>
                                            <input type="text" class="form-control form-control-sm" id="kode" :value="order.code" readonly>
                                        </td>
                                        <td>
                                            <input type="text" class="form-control form-control-sm" id="name" :value="order.name" readonly>
                                        </td>
                                        <td>
                                            <input type="text" class="form-control form-control-sm" id="harga" :value="order.price" readonly>
                                        </td>
                                        <td>
                                            <input type="text" class="form-control form-control-sm" id="stock" :value="order.stock" readonly>
                                        </td>
                                        <td>
                                            <input type="number" name="quantity[]" v-model="order.quantity" class="form-control form-control-sm" id="quantity" @keyup="hitungTotal($event, index)">
                                        </td>
                                        <td>
                                            <input type="text" class="form-control form-control-sm" :value="order.total" id="subtotal" readonly>
                                        </td>
                                        <td>
                                            <button type="button" class="btn btn-sm btn-danger" @click="hapusOrder(index, order)"><i class="fas fa-trash"></i></button>
                                        </td>
                                   </tr>
                               </tbody>
                               <tfoot>
                                   <tr>
                                       <th colspan="4" class="text-right">Subtotal</th>
                                       <td colspan="2">
                                           <input type="number" class="form-control form-control-sm" :value="grandTotal" readonly>
                                       </td>
                                   </tr>
                               </tfoot>
                           </table>
                        </div>
                    </div>
                    <div class="col-5 card">
                        <div class="card-header">
                            <p class="card-title">Detil Transaksi</p>
                        </div>
                        <div class="card-body">
                           <div class="row">
                               <div class="col-6 mb-2">
                                    <label for="grandtotal">Grand Total</label>
                               </div>
                               <div class="col-6 mb-2">
                                    <input type="number" class="form-control form-control-sm" name="grandtotal" :value="grandTotal" readonly>
                               </div>
                               <div class="col-6 mb-2">
                                    <label for="pembayaran">Pembayaran</label>
                               </div>
                               <div class="col-6 mb-2">
                                    <input type="number" class="form-control form-control-sm" name="pembayaran" v-model="pembayaran" id="pembayaran">
                               </div>
                               <div class="col-6 mb-2">
                                    <label for="kembalian">Kembalian</label>
                               </div>
                               <div class="col-6 mb-2">
                                    <input type="number" class="form-control form-control-sm" name="kembalian" :value="(pembayaran-grandTotal)" readonly>
                               </div>
                           </div>
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">Ubah</button>
                        </div>
                    </div>
                </form>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
            </div>
        </div>
    </div>
</div>

resources/views/transactions/sales/nota-kontan.blade.php
@extends('layouts.app')
@section('title', 'Dashoard')
@section('content-title', 'Dashoard')
@section('card-header', 'Grafik')
@section('breadcrumb', 'Dashoard')
@section('sub-breadcrumb', 'Grafik')

@section('content')
    @if (Session::get('success'))
        <div class="alert alert-success" role="alert">
            {{ Session::get('success') }}
        </div>
    @endif
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">Nota</h5>
                    <button class="btn btn-secondary float-right" type="button" onclick="window.print()">Cetak</button>
                </div>
                <div class="card-body border rounded">
                    <div class="row">
                        <div class="col-12 text-center mb-2">
                            <p>Toko ABC <br> Cihampelas Kab. Bandung Barat</p>
                        </div>
                        <table class="table">
                            <tr>
                                <th>Tanggal</th>
                                <td>: {{$sale->created_at}}</td>
                            </tr>
                            <tr>
                                <th>Kode Transaksi</th>
                                <td>: {{$sale->code}}</td>
                            </tr>
                        </table>
                        <div class="col-12 text-center">
                            <table class="table table-sm">
                                <thead>
                                    <th>Merek</th>
                                    <th>Harga</th>
                                    <th>Jumlah</th>
                                    <th>Total</th>
                                </thead>
                                <tbody>
                                    @php
                                        $grandTotal = 0
                                    @endphp
                                    @foreach ($sale->products as $item)
                                    <tr>
                                        <td>{{$item->name}}</td>
                                        <td>{{ rupiah($item->price) }}</td>
                                        <td>{{$item->pivot->quantity}}</td>
                                        <td>{{rupiah($item->pivot->quantity * $item->price)}}</td>
                                        @php
                                            $grandTotal += ( $item->pivot->quantity * $item->price )
                                        @endphp
                                    </tr>
                                    @endforeach
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <td colspan="3" class="text-right">Subtotal</td>
                                        <td>{{ rupiah($grandTotal) }}</td>
                                    </tr>
                                    <tr>
                                        <td colspan="3" class="text-right">Tunai</td>
                                        <td>{{ rupiah($sale->payment) }}</td>
                                    </tr>
                                    <tr>
                                        <td colspan="3" class="text-right">Kembalian</td>
                                        <td>{{ rupiah($sale->payment - $grandTotal) }}</td>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-6">

        </div>
    </div>
@endsection

@section('css')
    <style>
         @media print {
        /* styling goes here */
            .card-header, .nav-item, footer {
                display: none;
            }
            table thead th, table tbody tr td, table tfoot, body {
                color: black;
            }
        }
    </style>
@endsection

@push('script')
    <script>

    </script>
@endpush