routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('home');
});

Auth::routes([
    'regiter' => false
]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'startPage'])->name('home');
Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'index'])->name('dashboard');

Route::middleware('auth')->group(function(){
    // resource routes
    Route::resource('users', \App\Http\Controllers\UserController::class);
    Route::resource('sales', \App\Http\Controllers\SaleController::class);
    Route::resource('products', \App\Http\Controllers\ProductController::class);
    Route::resource('payments', \App\Http\Controllers\PaymentController::class);
    Route::resource('purchases', \App\Http\Controllers\PurchaseController::class);
    Route::resource('suppliers', \App\Http\Controllers\SupplierController::class);
    Route::resource('categories', \App\Http\Controllers\CategoryController::class);
    Route::resource('warehouses', \App\Http\Controllers\WarehouseController::class);
    Route::resource('roles-permissions', \App\Http\Controllers\RolePermissionController::class);

    // datatable routes
    Route::get('datatable/users', [\App\Http\Controllers\DataTablesController::class, 'getUsers']);
    Route::get('datatable/sales', [\App\Http\Controllers\DataTablesController::class, 'getSales']);
    Route::get('datatable/payments', [\App\Http\Controllers\DataTablesController::class, 'getPayments']);
    Route::get('datatable/products', [\App\Http\Controllers\DataTablesController::class, 'getProducts']);
    Route::get('datatable/suppliers', [\App\Http\Controllers\DataTablesController::class, 'getSuppliers']);
    Route::get('datatable/purchases', [\App\Http\Controllers\DataTablesController::class, 'getPurchases']);
    Route::get('datatable/activities', [\App\Http\Controllers\DataTablesController::class, 'getActivities']);
    Route::get('datatable/categories', [\App\Http\Controllers\DataTablesController::class, 'getCategories']);
    Route::get('datatable/warehouses', [\App\Http\Controllers\DataTablesController::class, 'getWarehouses']);
    Route::get('datatable/roles-permissions', [\App\Http\Controllers\DataTablesController::class, 'getRoles']);

    // additional routes
    Route::get('getproducts', [\App\Http\Controllers\SaleController::class, 'getProducts']);
    Route::get('get/sale/{id}', [\App\Http\Controllers\SaleController::class, 'getSale']);
    Route::get('get/purchase/{id}', [\App\Http\Controllers\PurchaseController::class, 'getPurchase']);
    Route::put('password/reset/manual', [\App\Http\Controllers\UserController::class, 'resetPassword']);
    Route::get('activities', [\App\Http\Controllers\ActivityController::class, 'index'])->name('activities.index');
    Route::get('get/permission/{id}', [\App\Http\Controllers\RolePermissionController::class, 'getPermission']);
    Route::get('get/user/{id}', [\App\Http\Controllers\RolePermissionController::class, 'getUserRole']);
    Route::post('roles-permissions/setup-permissions/{id}', [\App\Http\Controllers\RolePermissionController::class, 'updatePermission']);
    Route::post('roles-permissions/assign-role', [\App\Http\Controllers\RolePermissionController::class, 'asignRoleUser']);

    // report route
    Route::get('report/sales', [\App\Http\Controllers\ReportController::class, 'salesReport'])->name('reports.sales.index');
    Route::get('get/report/all', [\App\Http\Controllers\ReportController::class, 'getSalesAll']);
    Route::get('get/report/product', [\App\Http\Controllers\ReportController::class, 'getSalesProduct']);
    Route::get('report/purchases', [\App\Http\Controllers\ReportController::class, 'reportPurchasePage']);
    Route::get('report/purchases/filter', [\App\Http\Controllers\ReportController::class, 'getReportPurchases']);

});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- CSRF Token -->
  <meta name="csrf-token" content="{{ csrf_token() }}">

  <title>{{ config('app.name', 'Laravel') }} - @yield('title')</title>
  <link rel="icon" type="image/x-icon" href="{{asset('img/prams_brand.png')}}">

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{{asset('adminLTE/plugins/fontawesome-free/css/all.min.css')}}">
  <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{asset('adminLTE/dist/css/adminlte.min.css')}}">
  <!-- Start build your styles -->
  @yield('css')

</head>
<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        
        <!-- Navbar -->
        @include('layouts.navbar')
        <!-- /.navbar -->

        <!-- Main Sidebar Container -->
        @include('layouts.sidebar')
        <!-- /.sidebar -->

        <!-- Content Wrapper -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0">@yield('content-title')</h1>
                        </div>
                        <!-- /.col -->
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="#">@yield('breadcrumb')</a></li>
                                <li class="breadcrumb-item active">@yield('sub-breadcrumb')</li>
                            </ol>
                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- /.row -->
                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->

            <!-- Main content -->
            <div class="content" id="app">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="card">
                                <div class="card-header text-center">
                                    <h5 class="m-0">@yield('card-header')</h5>
                                </div>
                                <div class="card-body">
                                    @yield('content')
                                </div>
                            </div>
                        </div>
                        <!-- /.col-md-6 -->
                    </div>
                    <!-- /.row -->
                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->

        <!-- Main Footer -->
        <footer class="main-footer">
            <!-- To the right -->
            <div class="float-right d-none d-sm-inline bg-light rounded-pill px-2 pb-1">
                <a href="https://wa.me/6282117694669" target="_blank"><img src="{{asset('img/wa-icon.png')}}" alt="Whatsapp Icon"> Developer</a>
            </div>
            <!-- Default to the left -->
            <strong>Copyright &copy; 2021 <a href="#">Pramono</a>.</strong> All rights reserved.
        </footer>
        <!-- /.main Footer -->
    </div>
    <!-- ./wrapper -->

    <!-- REQUIRED SCRIPTS -->

    <!-- jQuery -->
    <script src="{{asset('adminLTE/plugins/jquery/jquery.min.js')}}"></script>
    <!-- Bootstrap 4 -->
    <script src="{{asset('adminLTE/plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
    <!-- AdminLTE App -->
    <script src="{{asset('adminLTE/dist/js/adminlte.min.js')}}"></script>
    <!-- Vue CDN -->
    <script src="https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js"></script>
    <!-- axios CDN -->
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <!-- Start Build Your Scripts -->
    @stack('script')

</body>
</html>

resources/views/layouts/navbar.blade.php
<nav class="main-header navbar navbar-expand navbar-dark">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link h4">Point Of Sales Application</a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link" href="{{ route('logout') }}"
            onclick="event.preventDefault();
                            document.getElementById('logout-form').submit();">
            {{ __('Logout') }}
        </a>

        <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
            @csrf
        </form>
        </div>
      </li>
    </ul>
  </nav>

resources/views/layouts/sidebar.blade.php
<aside class="main-sidebar sidebar-dark-primary">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
        <img src="{{asset('img/prams_brand.png')}}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">{{config('app.name')}}</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="info">
          <a href="{{ route( 'users.edit', ['user' => Auth::user()->id ] ) }}" class="d-block">Login as {{ ucwords(Auth::user()->name) }}</a>
        </div>
      </div>
      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            <li class="nav-header">Home</li>
            <li class="nav-item">
                <a href="{{ route('home') }}" class="nav-link @if( request()->is('home') ) active @endif">
                    <i class="nav-icon fas fa-home"></i>
                    <p>Beranda</p>
                </a>
            </li>
            @can('lihat dashboard')
            <li class="nav-item">
                <a href="{{ route('dashboard') }}" class="nav-link @if( request()->is('dashboard') ) active @endif">
                    <i class="nav-icon fas fa-chart-pie"></i>
                    <p>Dashboard</p>
                </a>
            </li>
            @endcan
            <li class="nav-header">Manajemen Transaksi</li>
            @can('lihat penjualan')
            <li class="nav-item">
                <a href="{{ route('sales.index') }}" class="nav-link @if(request()->is('sales')) active @endif">
                    <i class="nav-icon fas fa-cash-register"></i>
                    <p>Penjualan</p>
                </a>
            </li>
            @endcan
            @can('lihat pembelian')
            <li class="nav-item @if(request()->is('purchases') || request()->is('payments')) menu-open  @endif">
                <a href="#" class="nav-link">
                    <i class="nav-icon fas fa-shopping-cart"></i>
                    <p>
                        Pembelian<i class="right fas fa-angle-left"></i>
                    </p>
                </a>
                <ul class="nav nav-treeview">
                    <li class="nav-item">
                    <a href="{{ route('purchases.index') }}" class="nav-link @if(request()->is('purchases')) active @endif">
                        <i class="far fa-circle nav-icon"></i>
                        <p>Data Pembelian</p>
                    </a>
                    </li>
                    <li class="nav-item">
                    <a href="{{ route('payments.index') }}" class="nav-link @if(request()->is('payments')) active @endif">
                        <i class="far fa-circle nav-icon"></i>
                        <p>Pembayaran</p>
                    </a>
                    </li>
                </ul>
            </li>
            @endcan
            <li class="nav-header">Manajemen Produk</li>
            @can('lihat produk')
            <li class="nav-item">
                <a href="{{ route('products.index') }}" class="nav-link @if(request()->is('products')) active @endif">
                    <i class="nav-icon fas fa-th-large"></i>
                    <p>Produk</p>
                </a>
            </li>
            @endcan
            @can('lihat kategori')
            <li class="nav-item">
                <a href="{{ route('categories.index') }}" class="nav-link @if(request()->is('categories')) active @endif">
                    <i class="nav-icon fas fa-layer-group"></i>
                    <p>Kategori</p>
                </a>
            </li>
            @endcan
            @can('lihat gudang')
            <li class="nav-item">
                <a href="{{ route('warehouses.index') }}" class="nav-link @if(request()->is('warehouses')) active @endif">
                    <i class="nav-icon fas fa-warehouse"></i>
                    <p>Gudang</p>
                </a>
            </li>
            @endcan
            @can('lihat supplier')
            <li class="nav-item">
                <a href="{{ route('suppliers.index') }}" class="nav-link @if(request()->is('suppliers')) active @endif">
                    <i class="nav-icon fas fa-store"></i>
                    <p>Supplier</p>
                </a>
            </li>
            @endcan
            <li class="nav-header">Manajemen User</li>
            @can('lihat user')
            <li class="nav-item">
                <a href="{{ route('users.index') }}" class="nav-link @if(request()->is('users')) active @endif">
                  <i class="nav-icon fas fa-id-card-alt"></i>
                  <p>
                    Data User
                  </p>
                </a>
            </li>
            @endcan
            @can('lihat aktifitas user')
            <li class="nav-item"> 
                <a href="{{ route('activities.index') }}" class="nav-link @if(request()->is('activities')) active @endif">
                  <i class="nav-icon fas fa-eye"></i>
                  <p>
                    Aktifitas User
                  </p>
                </a>
            </li>
            @endcan
            @can('lihat role')
            <li class="nav-item">
                <a href="{{ route('roles-permissions.index') }}" class="nav-link @if(request()->is('roles-permissions')) active @endif">
                  <i class="nav-icon fas fa-key"></i>
                  <p>Hak Akses</p>
                </a>
            </li>
            @endcan
            <li class="nav-header">Laporan</li>
            @can('lihat laporan penjualan')
            <li class="nav-item">
                <a href="{{ route('reports.sales.index') }}" class="nav-link @if(request()->is('report/sales')) active @endif">
                    <i class="nav-icon fas fa-file-alt"></i>
                    <p>
                        Penjualan
                    </p>
                </a>
            </li>
            @endcan
            @can('lihat laporan pembelian')
            <li class="nav-item">
                <a href="#" class="nav-link">
                    <i class="nav-icon fas fa-file-alt"></i>
                  <p>
                    Pembelian
                  </p>
                </a>
            </li>
            @endcan
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>